/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Admin;
import clases.Cliente;
import static clases.utils.Colecciones.usuarios;
import static clases.utils.ConsoleIO.*;
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author TheElctrMsc_Gaming
 */
public class LogReg extends javax.swing.JFrame {

    private CardLayout itemCL;

    /**
     * Creates new form LogReg
     */
    public LogReg() {
        initComponents();

        ImageIcon img = new ImageIcon(".\\resources\\logo\\IconoJavaPop2.png");
        super.setIconImage(img.getImage());
        
        itemCL = (CardLayout) itemsPanel.getLayout();

        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        itemsPanel = new javax.swing.JPanel();
        loginCard = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        loginFields = new interfaz.loginFields();
        registerCard = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        registerFields = new interfaz.registerFields();
        buttonPanel = new javax.swing.JPanel();
        loginMenuButton = new javax.swing.JButton();
        registerMenuButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPop - Inicio de sesión");
        setBackground(new java.awt.Color(0, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 51));

        itemsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        itemsPanel.setLayout(new java.awt.CardLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginCardLayout = new javax.swing.GroupLayout(loginCard);
        loginCard.setLayout(loginCardLayout);
        loginCardLayout.setHorizontalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        loginCardLayout.setVerticalGroup(
            loginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(loginFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        itemsPanel.add(loginCard, "login");

        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerCardLayout = new javax.swing.GroupLayout(registerCard);
        registerCard.setLayout(registerCardLayout);
        registerCardLayout.setHorizontalGroup(
            registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerFields, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        registerCardLayout.setVerticalGroup(
            registerCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerFields, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemsPanel.add(registerCard, "register");

        buttonPanel.setBackground(new java.awt.Color(0, 0, 51));

        loginMenuButton.setText("Iniciar Sesión");
        loginMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuButtonActionPerformed(evt);
            }
        });

        registerMenuButton.setText("Registrarse");
        registerMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerMenuButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginMenuButton)
                .addGap(18, 18, 18)
                .addComponent(registerMenuButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuButtonActionPerformed
        // TODO add your handling code here:
        itemCL.show(itemsPanel, "login");
    }//GEN-LAST:event_loginMenuButtonActionPerformed

    private void registerMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerMenuButtonActionPerformed
        // TODO add your handling code here:
        itemCL.show(itemsPanel, "register");
    }//GEN-LAST:event_registerMenuButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginFields.emailErrorLabel.setText("");
        loginFields.passwordErrorLabel.setText("");
        boolean validUser = true;

        // Recoje los credenciales del usuario
        String correo = loginFields.getEmailField1().getText();
        String clave = new String(loginFields.getPasswordField1().getPassword());

        // Comprobamos si el correo es válido
        if (checkCorreo(correo)) {

            // Si la contraseña es valida
            if (checkClave(clave)) {
                if (correo.equals("admin@javapop.com") && clave.equals("admin")) {
                    // Abrir menu admin
                    new MenuAdmin();
                    this.dispose();
                } else {
                    validUser = false;
                    // Se comprueba que exista algún usuario con ese correo y contraseña
                    for (int i = 0; i < usuarios.size(); i++) {
                        if (usuarios.get(i).correo.equals(correo)) {
                            if (usuarios.get(i).clave.equals(clave)) {
                                // vv Abrir menu usuario con ese user vv
                                new MenuPrincipal(usuarios.get(i));
                                validUser = true;
                                this.dispose();
                                break;
                            }
                        }
                    }
                }
            } else {// Si la contraseña y el correo no coinciden con los de ningun usuario
                // JOptionPane.showMessageDialog(this, "Los datos introducidos son incorrectos", "Credenciales no válidos", JOptionPane.INFORMATION_MESSAGE);
                loginFields.passwordErrorLabel.setText("Contraseña inválida");
            }
        } else {
            // JOptionPane.showMessageDialog(this, "El correo no es válido", "Credenciales no válidos", JOptionPane.INFORMATION_MESSAGE);
            loginFields.emailErrorLabel.setText("Correo inválido");
        }

        if (!validUser) {
            JOptionPane.showMessageDialog(this, "No existe un usuario con el correo indicado, o la contraseña es incorrecta.\nPor favor revise los credenciales e intentelo de nuevo.", "Credenciales no válidos", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Borra todas las alertas de errores
        registerFields.emailErrorLabel.setText("");
        registerFields.passwordErrorLabel.setText("");
        registerFields.nameErrorLabel.setText("");
        registerFields.ppccErrorLabel.setText("");
        registerFields.ccErrorLabel.setText("");
        registerFields.idErrorLabel.setText("");

        // Variable auxiliar
        boolean validUser = true;

        // Recoje los creedenciales del usuario
        String correo = registerFields.getEmail();
        String clave = registerFields.getPassword();
        String name = registerFields.getNameSurname();
        String ccpp = registerFields.getPPCC();
        String ttcc = registerFields.getCC();
        String dni = registerFields.getID();

        // Comprobamos que el correo sea válido
        if (!checkCorreo(correo)) {
            registerFields.emailErrorLabel.setText("Correo inválido");
        } else if (!checkClave(clave)) {
            registerFields.passwordErrorLabel.setText("Contraseña inválido");
        } else if (!checkCodigoPostal(ccpp)) {
            registerFields.ppccErrorLabel.setText("Codigo postal inválido");
        } else if (!checkTarjetaCredito(ttcc)) {
            registerFields.ccErrorLabel.setText("Tarjeta de crédito inválido");
        } else if (!checkDni(dni)) {
            registerFields.idErrorLabel.setText("DNI inválido");
        } else {
            validUser = true;
            for (int i = 0; i < usuarios.size(); i++) {
                if (usuarios.get(i).correo.equals(correo)) {
                    registerFields.emailErrorLabel.setText("Correo en uso");
                    validUser = false;
                    break;
                }
            }
            
            // Si superamos todas estas comprobaciones el usuario es valido y entra al menú principal
            if (validUser) {
                System.out.println("si");
                Cliente user = new Cliente(correo, clave, name, dni, Integer.parseInt(ccpp), ttcc);
                usuarios.add(user);
                // vv Abrir menu usuario con ese user vv
                new MenuPrincipal(user);
                this.dispose();
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel itemsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginCard;
    private interfaz.loginFields loginFields;
    private javax.swing.JButton loginMenuButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel registerCard;
    private interfaz.registerFields registerFields;
    private javax.swing.JButton registerMenuButton;
    // End of variables declaration//GEN-END:variables
}
