/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import static clases.utils.Colecciones.*;
import static clases.utils.CheckFunctions.*;
import static clases.utils.Searching.*;
import clases.enumeradores.*;
import clases.*;
import clases.utils.IOCustomLib;

import javax.swing.ImageIcon;
import java.awt.CardLayout;
import java.util.ArrayList;

/**
 *
 * @author TheElctrMsc_Gaming
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private CardLayout camposCL;
    public Cliente user;
    private ArrayList<Producto> productosFiltrado;
    private int posicionMin;
    private int posicionMax;
    
    /**
     * Creates new form MenuPrincipal1
     */
    public MenuPrincipal(Cliente user) {
        initComponents();
        this.user = user;
        this.camposCL = (CardLayout) this.jPanel1.getLayout();
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        botonPerfil = new javax.swing.JButton();
        busquedaButton = new javax.swing.JButton();
        etiquetaBusqueda = new javax.swing.JLabel();
        claveBusqueda = new javax.swing.JTextField();
        comboBoxCategoria = new javax.swing.JComboBox<>();
        etiquetaCategoria = new javax.swing.JLabel();
        botonSubir = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(100, 30), new java.awt.Dimension(60, 30), new java.awt.Dimension(100, 30));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 100), new java.awt.Dimension(60, 100), new java.awt.Dimension(80, 100));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 100), new java.awt.Dimension(60, 100), new java.awt.Dimension(80, 100));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(80, 80), new java.awt.Dimension(80, 30), new java.awt.Dimension(80, 80));
        jPanel1 = new javax.swing.JPanel();
        panelBienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCompra = new javax.swing.JPanel();
        productoMin1 = new interfaz.panels.ProductoMin();
        productoMin2 = new interfaz.panels.ProductoMin();
        productoMin3 = new interfaz.panels.ProductoMin();
        productoMin4 = new interfaz.panels.ProductoMin();
        productoMin5 = new interfaz.panels.ProductoMin();
        productoMin6 = new interfaz.panels.ProductoMin();
        productoMin7 = new interfaz.panels.ProductoMin();
        productoMin8 = new interfaz.panels.ProductoMin();
        rePag = new javax.swing.JButton();
        etiquetaPagina = new javax.swing.JLabel();
        avPag = new javax.swing.JButton();
        panelPerfil = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaPop - Menú Principal\n");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        banner.setBackground(new java.awt.Color(51, 153, 255));
        banner.setForeground(new java.awt.Color(0, 0, 51));

        botonPerfil.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        botonPerfil.setText("Mi perfil");
        botonPerfil.setPreferredSize(new java.awt.Dimension(130, 23));

        busquedaButton.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        busquedaButton.setText("Buscar");
        busquedaButton.setPreferredSize(new java.awt.Dimension(130, 23));
        busquedaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaButtonActionPerformed(evt);
            }
        });

        etiquetaBusqueda.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        etiquetaBusqueda.setText("Buscar:");

        claveBusqueda.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        claveBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveBusquedaActionPerformed(evt);
            }
        });

        comboBoxCategoria.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        comboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moda y acesorios", "Tv, audio y foto", "Moviles y telefónica", "Informática y electrónica", "Consolas y videojuegos", "Deporte y ocio" }));

        etiquetaCategoria.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        etiquetaCategoria.setText("Categoría:");

        botonSubir.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        botonSubir.setText("Subir producto");
        botonSubir.setPreferredSize(new java.awt.Dimension(110, 23));
        botonSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSubirActionPerformed(evt);
            }
        });

        Logo.setFont(new java.awt.Font("OCR A Extended", 0, 36)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 0, 51));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new ImageIcon(".\\resources\\logo\\IconoJavaPop3.png"));
        Logo.setText("JavaPop");
        Logo.setPreferredSize(new java.awt.Dimension(230, 38));
        Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaBusqueda, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(bannerLayout.createSequentialGroup()
                        .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(busquedaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(claveBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bannerLayout.createSequentialGroup()
                        .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bannerLayout.createSequentialGroup()
                                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(etiquetaBusqueda)
                                    .addComponent(claveBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(busquedaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaCategoria)))
                            .addGroup(bannerLayout.createSequentialGroup()
                                .addComponent(botonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonSubir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido a JavaPop!\n");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new ImageIcon(".\\resources\\logo\\animat-shopping-cart-color.gif"));

        javax.swing.GroupLayout panelBienvenidaLayout = new javax.swing.GroupLayout(panelBienvenida);
        panelBienvenida.setLayout(panelBienvenidaLayout);
        panelBienvenidaLayout.setHorizontalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBienvenidaLayout.setVerticalGroup(
            panelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelBienvenida, "Bienvenida");

        rePag.setText("<<");
        rePag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePagActionPerformed(evt);
            }
        });

        etiquetaPagina.setText("Página 0 de 100");

        avPag.setText(">>");
        avPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCompraLayout = new javax.swing.GroupLayout(panelCompra);
        panelCompra.setLayout(panelCompraLayout);
        panelCompraLayout.setHorizontalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addComponent(productoMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompraLayout.createSequentialGroup()
                        .addComponent(productoMin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productoMin8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rePag)
                .addGap(18, 18, 18)
                .addComponent(etiquetaPagina)
                .addGap(18, 18, 18)
                .addComponent(avPag)
                .addContainerGap())
        );
        panelCompraLayout.setVerticalGroup(
            panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productoMin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productoMin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productoMin8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rePag)
                    .addComponent(avPag)
                    .addComponent(etiquetaPagina)))
        );

        jPanel1.add(panelCompra, "Compra");

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        jPanel1.add(panelPerfil, "Perfil");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filler4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                    .addComponent(filler3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void claveBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveBusquedaActionPerformed

    private void busquedaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaButtonActionPerformed
        camposCL.show(jPanel1, "Compra");

        // Limpiamos la lista filtrada de productos
        productosFiltrado.clear();
        
        // Se filtran los productos por categoría
        Categoria cat = getCategoria(comboBoxCategoria.getSelectedIndex());
        for (int i = 0; i < productos.size(); i++) {
            if (productos.get(i).getCategoria() == cat) {
                if (!productos.get(i).getVendedor().equals(user)) {
                    productosFiltrado.add(productos.get(i));
                }
            }
        }

        // Se pidan unas palabras clave
        String kW = claveBusqueda.getText();
        String[] keyWords = kW.split(" ");

        // Se actualizan los parametros de busqueda de los productos
        for (int i = 0; i < productosFiltrado.size(); i++) {
            updateTags(user, productosFiltrado.get(i), keyWords);
        }
        
        // Si se han introducido palabras clave quitamos los productos sin coincidencias
        if (!kW.equals("")) {
            for (int i = 0; i < productosFiltrado.size(); i++) {
                if (productosFiltrado.get(i).getMatchDeg() == 0) {
                    productosFiltrado.remove(i);
                    i--;
                }
            }
        }

        // Se organizan los productos
        sort(productosFiltrado, 0, productosFiltrado.size() - 1);

        // Establece la posición mínima y máxima de los productos mostrados en 0
        posicionMin = 0;
        posicionMax = 0;
        
        // Actualiza la posicion mínima y máxima y muestra los productos
        displayProductos(); 

        // Activa o desactiva los botones para cambiar páginas de productos según sea necesario
        lockUnlockBotonesComprar();
        
        // Cambia el texto de la etiqueta que indica en que página estamos
        etiquetaPagina.setText("Página " + (posicionMin / 8 + 1) + " de " + (productosFiltrado.size() / 8 + 1));
    }//GEN-LAST:event_busquedaButtonActionPerformed

    private void displayProductos() {
        // actualizamos posicionMax
        for (int i = posicionMin + 1; i <= posicionMin + 9; i++) {
            posicionMax = posicionMin + i - 1;
            if (posicionMax < productosFiltrado.size()) {
                //System.out.println((i) + ".- " + productosFiltrado.get(posicionMax).getTitulo());
            } else {
                posicionMax--;
                break;
            }
        }

        // mostramos los productos corresponcientes
        for (int i = posicionMin; i <= posicionMax; i++) {
            switch (i % 8) {
                case 0:
                    productoMin1.setProducto(productosFiltrado.get(i));
                    productoMin1.setVisible(true);
                    break;
                case 1:
                    productoMin2.setProducto(productosFiltrado.get(i));
                    productoMin2.setVisible(true);
                    break;
                case 2:
                    productoMin3.setProducto(productosFiltrado.get(i));
                    productoMin3.setVisible(true);
                    break;
                case 3:
                    productoMin4.setProducto(productosFiltrado.get(i));
                    productoMin4.setVisible(true);
                    break;
                case 4:
                    productoMin5.setProducto(productosFiltrado.get(i));
                    productoMin5.setVisible(true);
                    break;
                case 5:
                    productoMin6.setProducto(productosFiltrado.get(i));
                    productoMin6.setVisible(true);
                    break;
                case 6:
                    productoMin7.setProducto(productosFiltrado.get(i));
                    productoMin7.setVisible(true);
                    break;
                case 7:
                    productoMin8.setProducto(productosFiltrado.get(i));
                    productoMin8.setVisible(true);
                    break;
            }
        }

        // ponemos invisibles las casillas que no deban tener producto
        for (int i = posicionMax + 1; i < posicionMin + 8; i++) {
            switch (i % 8) {
                case 0:
                    productoMin1.setVisible(false);
                    break;
                case 1:
                    productoMin2.setVisible(false);
                    break;
                case 2:
                    productoMin3.setVisible(false);
                    break;
                case 3:
                    productoMin4.setVisible(false);
                    break;
                case 4:
                    productoMin5.setVisible(false);
                    break;
                case 5:
                    productoMin6.setVisible(false);
                    break;
                case 6:
                    productoMin7.setVisible(false);
                    break;
                case 7:
                    productoMin8.setVisible(false);
                    break;
                default:
                    break;
            }
        }
    }
    
    private void lockUnlockBotonesComprar() {
        if (posicionMin - 10 < 0) {
            rePag.setEnabled(false);
        } else {
            rePag.setEnabled(true);
        }

        if (posicionMin + 10 >= productosFiltrado.size()) {
            avPag.setEnabled(false);
        } else {
            avPag.setEnabled(true);
        }
    }
    
    private void rePagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePagActionPerformed
        // Disminuye la posición mínima de los productos mostrados en 8
        posicionMin -= 8;
        
        // Actualiza la posicion mínima y máxima y muestra los productos
        displayProductos(posicionMin + 1);

        // Activa o desactiva los botones para cambiar páginas de productos según sea necesario
        lockUnlockBotonesComprar();
        
        // Cambia el texto de la etiqueta que indica en que página estamos
        etiquetaPagina.setText("Página " + (posicionMin / 8 + 1) + " de " + (productosFiltrado.size() / 8));
    }//GEN-LAST:event_rePagActionPerformed

    private void avPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avPagActionPerformed
        // Aumenta la posición mínima de los productos mostrados en 8
        posicionMin += 8;
        
        // Actualiza la posicion mínima y máxima y muestra los productos
        displayProductos(posicionMin + 1);

        // Activa o desactiva los botones para cambiar páginas de productos según sea necesario
        lockUnlockBotonesComprar();
        
        // Cambia el texto de la etiqueta que indica en que página estamos
        etiquetaPagina.setText("Página " + (posicionMin / 8 + 1) + " de " + (productosFiltrado.size() / 8 + 1));
    }//GEN-LAST:event_avPagActionPerformed

    private void botonSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSubirActionPerformed
        new MenuNuevoProducto(this);
    }//GEN-LAST:event_botonSubirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        IOCustomLib.guardarClientes(usuarios);
        IOCustomLib.guardarProductos(productos);
        IOCustomLib.guardarVentas(ventas);
    }//GEN-LAST:event_formWindowClosing

    private void LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoMouseClicked
        camposCL.show(jPanel1, "Bienvenida");
    }//GEN-LAST:event_LogoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton avPag;
    private javax.swing.JPanel banner;
    private javax.swing.JButton botonPerfil;
    private javax.swing.JButton botonSubir;
    private javax.swing.JButton busquedaButton;
    private javax.swing.JTextField claveBusqueda;
    private javax.swing.JComboBox<String> comboBoxCategoria;
    private javax.swing.JLabel etiquetaBusqueda;
    private javax.swing.JLabel etiquetaCategoria;
    private javax.swing.JLabel etiquetaPagina;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelCompra;
    private javax.swing.JPanel panelPerfil;
    private interfaz.panels.ProductoMin productoMin1;
    private interfaz.panels.ProductoMin productoMin2;
    private interfaz.panels.ProductoMin productoMin3;
    private interfaz.panels.ProductoMin productoMin4;
    private interfaz.panels.ProductoMin productoMin5;
    private interfaz.panels.ProductoMin productoMin6;
    private interfaz.panels.ProductoMin productoMin7;
    private interfaz.panels.ProductoMin productoMin8;
    private javax.swing.JButton rePag;
    // End of variables declaration//GEN-END:variables
}
